language: python
python: "3.5"
env:
 - CC="gcc" CXX="g++-4.8"
before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -y cabal-install g++-4.8
install:
 - cabal update
 - cabal install primes
script: "./tools/check.py"
